config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :experiences, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  get "dashboard", to: "users#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, class_name: 'User'
  belongs_to :experience

  def past?
    end_on < Date.today
  end

  def booking_price
    self.price = ((end_on - start_on) * experience.price).ceil
  end
end

app/models/categorizing.rb
class Categorizing < ApplicationRecord
  belongs_to :experience
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizings
  has_many :experiences, through: :categorizings

  validates :name, presence: true, uniqueness: true

  scope :featured, lambda { |number|
    select('categories.*')
      .joins(:categorizings)
      .having('count(*) >= ?', number)
      .order(Arel.sql('random()'))
      .limit(3)
      .group('categories.id')
  }
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  has_many :bookings
  has_many :categorizings, dependent: :destroy
  has_many :categories, through: :categorizings
  has_many :reviews, dependent: :destroy

  validates :title, presence: true, uniqueness: true, null: false
  validates :description, presence: true, null: false
  validates :price, presence: true, null: false, numericality: { only_integer: true }
  validates :picture_url, null: false
  # validates :photo, presence: true
  validates :categories, presence: true

  accepts_nested_attributes_for :categories

  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :rating, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :experiences, foreign_key: :owner_id
  has_many :bookings, foreign_key: :renter_id

  has_many :favourites, foreign_key: :favoruite_id

  has_many :reviews, foreign_key: :review_id

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new(booking_params)
    @booking.experience = @experience
    @booking.renter = current_user
    @booking.booking_price
    if @booking.save
      redirect_to dashboard_path
    else
      render 'experiences/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_on, :end_on)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        experiences.title @@ :query \
        OR categories.name @@ :query \
      "
      @experiences = Experience.joins(:categories).where(sql_query, query: "%#{params[:query]}%")
      empty_search_message = "Sorry #{params[:query].capitalize} could not found, have a look at what else is on offer"
    else
      @experiences = Experience.all
    end
    redirect_to experiences_path, flash: { empty_search: empty_search_message } if @experiences.empty?
  end

  def show
    @recent_experiences = Experience.last(3)
    @experience = Experience.find(params[:id])
    @booking = Booking.new
  end

  def new
    @experience = Experience.new
  end

  def create
    @review = Review.new
    @experience = Experience.new(experience_params)
    @experience.owner = current_user
    @experience.categories = Category.where(id: category_ids)
    if @experience.save
      redirect_to @experience
    else
      render :index
    end
  end

  def update
    @experience = Experience.find(params[:id])
    @experience.owner = current_user
    @experience.categories = Category.where(id: category_ids)
    if @experience.update(experience_params)
      redirect_to experience_path
    else
      render 'experiences/show'
    end
  end

  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy
    redirect_to dashboard_path
  rescue ActiveRecord::InvalidForeignKey
    redirect_to @experience, alert: "You can't delete a booked experience."
  end

  private

  def category_ids
    params[:experience][:category_ids]
  end

  def experience_params
    params.require(:experience).permit(:title, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @recent_experiences = Experience.last(3)
    @featured_categories = Category.featured(3)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @review.user_id = current_user.id
    @experience = Experience.find(params[:experience_id])
    @review.experience = @experience
  end

  def create
    @review = Review.new(review_params)
    @experience = Experience.find(params[:experience_id])

    @review.user_id = current_user.id
    @review.experience = @experience

    if @review.save
      redirect_to experience_path(params[:experience_id])
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @review = Review.new
    @experiences = current_user.experiences
    @bookings = current_user.bookings
    # @owner_experiences = @experiences.owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<h2><strong>$<%= @experience.price %>/day</strong></h2>
<hr>
<%= simple_form_for [@experience, @booking] do |f| %>
  <%= f.input :start_on, html5: true, as: :date %>
  <%= f.input :end_on, html5: true, as: :date %>

  <%= f.hidden_field :experience_price, value: @experience.price %>
  <hr>
  <h3>Total: <span class="booking-total-price">   <i class="fas fa-spinner fa-pulse"></i>
</span></h3>
<hr>
  <%= f.button :submit, class: 'btn btn-primary mb-3 modal-submit w-100', id: 'book-experience' %>
<% end %>

app/views/bookings/_confirm_booking_details_modal.html.erb
<!-- The Modal -->
<div class="modal fade modal-sm" id="confirmBooking">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Confirm Experience</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div id="booking-info">
          <p>
            <strong>booking-start-date:</strong>
            <span id="booking-start-date"></span>
          </p>

          <p>
            <strong>booking-end-date:</strong>
            <span id="booking-end-date"></span>
          </p>

          <p>
            <strong>booking-total-price:</strong>
            <span id="booking-total-price"></span>
          </p>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

app/views/experiences/_card.html.erb
<div class="card-product m-3">
  <%= cl_image_tag experience.photo, class: 'img' %>
  <div class="card-product-infos p-3">
    <%= link_to experience_path(experience.id) do %>
    <h2><%= experience.title %></h2>
    <% end %>
    <p class="mt-2"><%= experience.description %></p>
    <h3 class="mb-3">$<%= experience.price %>/day</h3>
    <%= render 'experiences/update_experience_modal', resource: experience do %>
      <%= simple_form_for experience do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.association :categories,
                include_hidden: false,
                input_html: { multiple: true }  %>
        <%= f.input :price %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="buttons justify-content-between">
          <%= f.button :submit, class: 'btn btn-primary' %>
          <%= f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="card-product-actions p-3">
    <% if experience.owner == current_user %>
      <%= link_to " ", experience_path(experience),
        class: 'trash fas fa-trash-alt',
        method: :delete,
        data: { confirm: "Are you sure you want to delete: #{experience.title}?" } %>
    <% end %>
  </div>
</div>

app/views/experiences/_form.html.erb
<%= simple_form_for experience do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :categories,
                    include_hidden: false,
                    input_html: { multiple: true }  %>
  <%= f.input :price %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>


  <div class="buttons d-flex justify-content-between">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" %>
  </div>
<% end %>

app/views/experiences/_not_found.html.erb
<p>Sorry we can't find a similar experience</p>

app/views/experiences/_update_experience_modal.html.erb
<% modal_id = "modal#{resource.class}#{resource.id}" %>

<!-- Button to Open the Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#<%= modal_id %>">
  Edit Experience <i class="fas fa-edit"></i>
</button>

<!-- The Modal -->
<div class="modal fade" id=<%= modal_id %>>
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Edit Your Experience Listing</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/experiences/index.html.erb
<div class="container" id="index-page">
  <h2 class="mt-3">All experiences</h2>
  <%= render 'shared/search_form' %>
  <div class="error-message mt-2">
    <% if flash[:empty_search] %>
    <p><%= flash[:empty_search] %></p>
    <% end %>
  </div>
</div>


<div class="row">
  <% @experiences.each do |experience| %>
  <div class="col-lg-4 col-sm-12">
    <%= link_to experience_path(experience.id) do %>
      <div class="card-trip card-zoom mt-4">
       <% if experience.photo.present? %>
            <%= cl_image_tag experience.photo, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
            <% else %>
            <%= image_tag experience.picture_url, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
            <% end %>
        <div class="card-trip-infos">
          <div>
            <h2 class="mb-1"><%= experience.title %></h2>
            <p><%= experience.description %></p>
          </div>
        </div>
          <div class="card-category">
            <% experience.categories.each do |category| %>
              <span class="badge badge-info p-1"><%= category.name %></span>
            <% end %>
          </div>

          <div class="card-trip-price">
            <h3> $<%= experience.price %>/day</h3>
          </div>


      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/experiences/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= render 'form', experience: @experience %>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
</div>

<div class="container-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('  <% if @experience.photo? %><%= cl_image_path @experience.photo, class: '' %><% else %><%= cl_image_path @experience.picture_url, class: 'card-img-top mb-3' %><% end %>');background-size:cover;background-position:center; background-attachment: fixed;height:80vh;">

  <div class="row align-items-end h-100 p-5">
    <div class="col-xs col-sm-6">
      <h1 class="text-white"><%= @experience.title %></h1>

        <% if current_user == @experience.owner %>
         <%= render 'experiences/update_experience_modal', resource: @experience do %>
          <%= render 'form', experience: @experience %>
          <% end %>
        <% else %>
          <% if @experience.owner.name %><p class="text-white"><strong>The original owner of this experience is </strong> <%= @experience.owner.name  %> <% end %> </p>
        <% end %>

      </div>


  </div>
</div>

<div class="container show-page-individual">
  <div class="row">
    <div class="col-xs col-sm-7 mt-4 order-xs-2">

      <p><%= @experience.description %></p>
      <hr>
      <p><strong>Your cortex will embody the following states upon injecting this experience:<br></strong>
        <% @experience.categories.each do |category| %>
          <span class="badge badge-info"><%= category.name %></span>
        <% end %>
      </p>

      <h2 class="mt-5 mb-3">Reviews (<%= @experience.reviews.length %>)</h2>
      <div class="card pl-4 pr-4 pt-4">
        <% @experience.reviews.each do |review| %>
          <div class="row align-items-center pb-4">
            <div class="col-3">
              <%= image_tag "user.png", class: 'img-fluid' %>
            </div>
            <div class="col-9">
              <p><%= review.content %></p>
              <p><strong> <i><%= review.user.name ? review.user.name : "Bob Loblaw" %></i></strong></p>
              <p><% review.rating.to_i.times do |star| %>
                  <i class="fas fa-star"></i>
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
        </div>
      </div>

      <div class="col-xs col-sm-4 align-self-start sticky-top order-xs-1" style="margin-top:-100px">
        <% if current_user != @experience.owner %>
          <div class="card mb-5 p-4 ">
            <%= render 'bookings/booking_form' %>
          </div>
        <% end %>
      </div>
    </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AIRSPERIENCE | Access the collective consciousness and experience things you're too late/lazy to do yourself.</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <div class="footer mt-5">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
       AIRSPERIENCE © 2034 | All Rights Reserved
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
</div>

<%= render 'components/home_slider' %>

<div class="container">

  <div id="how" class="row mt-5 mb-5 text-center">

    <div class="col-12 mt-4 mb-4">
      <h2>How does it work?</h2>
    </div>

    <div class="col-4">
      <div class="card card-zoom" style="min-height: 382px;">
        <div class="card-body">
          <%= image_tag "icons/1-search.png", alt: "", class: "mb-3" %>
          <h5 class="card-title">Search our repository</h5>
          <p class="card-text"> Search our colourful and diverse collection of experiences from users around the world. Ever wondered what it's like to feed a wild boar? Let's go there.</p>
          <%= link_to 'Browse Experiences', experiences_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-4">

      <div class="card card-zoom" style="min-height: 382px;">
        <div class="card-body">
          <%= image_tag "icons/2-load.png", alt: "", class: "mb-3" %>
          <h5 class="card-title">Rent the experience</h5>
          <p class="card-text">Choose how long you want to own this experience -- download it onto your BCI as many times as you want during this period (we won't judge).</p>
          <%= link_to 'Recent Experiences', '#recent', class: 'btn btn-primary' %>
        </div>
      </div>

    </div>

    <div class="col-4">

      <div class="card card-zoom" style="min-height: 382px;">
        <div class="card-body">
          <%= image_tag "icons/3-superhuman.png", alt: "Become a superhuman", class: "mb-3" %>
          <h5 class="card-title">Return, rinse and repeat</h5>
          <p class="card-text">Feel like and be a better human after enriching your own life expereince, without lifting a finger. Once your rental period is done, you give that experience back.</p>
          <%= link_to 'Sign up today', new_user_registration_path, class: 'btn btn-primary' %>
        </div>
      </div>

    </div>

  </div>

</div>

<div class="container-fluid full-width-highlight pt-3 pb-5">

    <div class="col-12 text-center mt-5 bmb-5">
      <h2><strong> Your brain doesn't know the difference!</strong></h2><br><h5 class="text-white pl-5 pr-5"> Actualize your dreams of meeting Keanu Reeves on the Subway --<br>the feelings will stay long after your download your experience.</h5>
    </div>
  </div>

</div>

<div class="container mb-5" id="home">


  <div class="py-3">
    <div class="row">
      <h2 class="col-6">Recent Experiences</h2>
      <div class="col-6">
        <%= link_to 'View all', experiences_path, class: 'btn btn-primary float-right mb-0' %>
      </div>
    </div>
    <div class="row">
      <% @recent_experiences.each do |experience| %>
      <div class="col-4">
        <%= link_to experience_path(experience.id) do %>

          <div class="card-trip card-zoom">
          <% if experience.photo.present? %>
               <%= cl_image_tag experience.photo, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
               <% else %>
               <%= image_tag experience.picture_url, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
               <% end %>

            <div class="card-trip-infos">
              <div>
                <h2 class="mb-1"><%= experience.title %></h2>
                <p><%= experience.description %></p>
              </div>
            </div>
              <div class="card-category">
                <% experience.categories.each do |category| %>
                   <span class="badge badge-info p-1"><%= category.name %></span>
                 <% end %>
              </div>
            <div class="card-trip-footer">
              <h2 class="card-trip-pricing">$<%= experience.price %>/day</h2>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

  <% @featured_categories.each do |category| %>
    <div class="category-wrapper py-3 ">
      <h2><%= category.name %></h2>
      <div class="row">
        <% category.experiences.each do |experience| %>
          <div class="col-4">
            <%= link_to experience_path(experience.id) do %>

              <div class="card-trip card-zoom">
                <% if experience.photo.present? %>
                     <%= cl_image_tag experience.photo, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
                     <% else %>
                     <%= image_tag experience.picture_url, height: 180, width: 290, class: 'card-img-top', crop: :thumb %>
                     <% end %>
                <div class="card-trip-infos">
                  <div>
                    <h2 class="mb-1"><%= experience.title %></h2>
                    <p><%= experience.description %></p>
                  </div>
                  <h2 class="card-trip-pricing">$<%= experience.price %></h2>
                </div>
                <div class="card-trip-footer p-2">
                  <% experience.categories.each do |category| %>
                     <span class="badge badge-info p-1"><%= category.name %></span>
                   <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/_new.html.erb
<%= simple_form_for [experience, @review], url: experience_reviews_path(experience.id) do |f| %>
    <%= f.input :content, as: :text, label: 'Your Review' %>
    <%= f.input :rating %>
    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'new' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
  <%= form_tag(experiences_path, method: :get) do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search for an experience...', 'aria-describedby': 'search-submit'  %>
      <div class="input-group-append">
        <%= submit_tag 'Search', name: nil, class: 'btn btn-primary', id: 'search-submit' %>
      </div>
    </div>
  <% end %>

app/views/users/_past_experiences.html.erb
<h2>Past Experiences</h2>

<% @bookings.each do |booking| %>
  <% if booking.end_on < Date.today %>

  <div class="col-4">
    <div class="card-trip">
          <%= cl_image_tag booking.experience.photo, height: 180, width: 290, crop: :thumb, class: 'w-100' %>
      <div class="card-trip-infos">
        <div>
          <h2 class="mb-1"><%= booking.experience.title %></h2>
          <p class="mb-1"><%= booking.experience.description %></p>
          <p><strong>Starts on:</strong> <%= booking.start_on.strftime('%w %B, %Y') %></p>
          <p><strong>Ends on:</strong> <%= booking.end_on.strftime('%w %B, %Y') %></p>
        </div>
          <h2 class="card-trip-pricing">$<%= booking.price %></h2>
      </div>
      <div class="edit">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#postReview">
          Leave a review
        </button>
      </div>
  </div>


  <div class="modal fade" id="postReview" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Leave a review for <%=booking.experience.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <%= render 'reviews/new', experience: booking.experience %>

      </div>
    </div>
  </div>
</div>

  <% end %>
<% end %>

app/views/users/dashboard.html.erb
<div class="container">
  <div class="row">
    <h2 class="mb-4 mt-4 col-6">Booked Experiences (<%= @bookings.count %>)</h2>
  </div>
  <% @bookings.each do |booking| %>
    <div class="card-product m-3">
    <%= cl_image_tag booking.experience.photo, crop: :thumb, height: 220, width: 240%>
    <div class="card-product-infos py-3 pl-3 pr-5">
      <h3><%= booking.start_on.strftime('%w %B, %Y') %> - <%= booking.end_on.strftime('%w %B, %Y') %></h3>
      <%= link_to experience_path(booking.experience.id) do %>
      <h2><%= booking.experience.title %></h2>
    <% end %>
      <p class="mt-3 mb-4"><%= booking.experience.description %></p>
        <div>
          <a class="btn btn-primary" href="">Download Experience   <i class="fas fa-cloud-download-alt"></i></a>
        </div>
      </div>
    </div>
    <% end %>
</div>

<div class="container">
  <div class="row">
    <h2 class="mb-4 mt-4 col-6">Listed Experiences (<%= @experiences.count %>)</h2>
  </div>
  <% @experiences.each do |experience| %>
    <% if experience.owner == current_user %>
      <%= render "experiences/card", experience: experience %>
    <% end %>
  <% end %>
</div>